version: '3'

services:
  mongo:
    image: mongo
    container_name: mongo01
    ports:
      - "27017:27017"
    networks:
      labs:
        ipv4_address: 172.20.0.3

  redis:
    image: redis/redis-stack:latest
    container_name: redis01
    ports:
      - "6379:6379"
      - "8001:8001"
    networks:
      labs:
        ipv4_address: 172.20.0.2

  app:
    build:
      context: .
    container_name: api_app
    ports:
      - "${PORT}:3000"
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - MONGO_URI=${MONGO_URI}
    depends_on:
      - mongo
      - redis
    networks:
      labs:
        ipv4_address: 172.20.0.4

networks:
  labs:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
